### ISSUE TITLE
Can't get it to work?

### ISSUE THREAD

**Issue by MikeyProgrammer** [LLukas22/PropertyInterception#1]
I'm writing a simple .NET Core 3.1 console application to test out your library, I've done everything your home page says to do and it compiles and runs just fine it's just that it never hits the interception code.

    public partial class BasicClass
    {
        [Interception]
        public string LastName;
    }
    
    It never hits my Interception Attribute code:
    
        internal class InterceptionAttribute : Attribute, IPropertyGetterInterceptor, IPropertySetterInterceptor
    {
        public InterceptionAttribute()
        {
            int i = 9;
        }

        public bool OnException(PropertyInterceptionInfo propertyInterceptionInfo, Exception exception)
        {
            //Do Something on Error
            return false;
        }

        public void OnExit(PropertyInterceptionInfo propertyInterceptionInfo)
        {
            //Do Something on Exit
        }

        public void OnGet(PropertyInterceptionInfo propertyInterceptionInfo, object currentValue)
        {
            //Do Something on Get
            int i = 9;
        }

        public bool OnSet(PropertyInterceptionInfo propertyInterceptionInfo, object oldValue, object newValue)
        {
            //Do Something on Set
            return true;
        }
    }

**Comment by LLukas22** [comment]
Ok, there are 2 possible problems here.

First the property you are applying your attribute on must be **protected** or **private** and should start with a **lowercase letter**.
The generator will then generate a public property with the same name but an uppercase letter.
You should try to change your example to this:

```
public partial class BasicClass
{
    [Interception]
    private string lastName;
}
```

Second the support for source-generators in .NetCore3.1 or C#8 isn't that good. Thats probably why you don't get any errors while  compiling the project. If you use .NET 5 or greater you can actually see the output of the generator under Solution ->Dependencies->Analyzers ->PropertyInterception.
![grafik](https://user-images.githubusercontent.com/65088241/182190422-89282495-c066-40e6-9e46-c57a5da2c0a6.png)
